-- 2026-09-09 · #15 · inventory_checks.shelf_positions 컬럼 DROP · products 단일 소스 완성
--   · 사용자 지시 · optimal_stock 원칙 동일 · products.shelf_positions 유일 소스
--
-- ⚠️ 파괴적 SQL · 사용자 명시 확인 후 실행
-- ⚠️ 반드시 순서 준수 · 백필 완료 후 DROP
--
-- 1단계 · 필수 · 기존 스냅샷 → products 마스터 백필 (아직 안 했으면)
-- UPDATE products p
-- SET shelf_positions = ic.shelf_positions
-- FROM (
--   SELECT DISTINCT ON (product_code) product_code, shelf_positions
--   FROM inventory_checks
--   WHERE shelf_positions IS NOT NULL AND shelf_positions != '{}'::jsonb
--   ORDER BY product_code, checked_at DESC
-- ) ic
-- WHERE p.product_code = ic.product_code
--   AND (p.shelf_positions IS NULL OR p.shelf_positions = '{}'::jsonb);
--
-- 2단계 · 백필 검증 (실행 전 확인)
-- SELECT COUNT(*) AS total FROM inventory_checks WHERE shelf_positions IS NOT NULL AND shelf_positions != '{}'::jsonb;
-- SELECT COUNT(*) AS migrated FROM products WHERE shelf_positions IS NOT NULL AND shelf_positions != '{}'::jsonb;
--
-- 3단계 · DROP · 백필 검증 후 실행
ALTER TABLE inventory_checks DROP COLUMN IF EXISTS shelf_positions;
