-- 2026-10-04 · ERP Sale_Status → Supabase sales 테이블 신규 생성
--
-- 사용자 지시 (SALE 1차 구현):
--   · ERP Sale_Status 8개 field 그대로 저장 (추측 field 추가 금지)
--   · 안정적 transaction identity 미확보 상태 · PCode/BmCode/ROWNUM 등 임의 추가 X
--   · DB 내부 관리용 (id · created_at) 만 추가
--   · 중복 INSERT 방지는 조회기간 단위 상태 표시로 처리 (스키마 레벨 unique 안 함)
--
-- 실행:
--   · 사용자가 Supabase SQL Editor 에서 수동 실행
--   · 자동 실행 금지

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sale_date DATE,
    product_name TEXT,
    buyer_name TEXT,

    total_stock NUMERIC,
    unit_cost NUMERIC,
    unit_sale NUMERIC,
    sale_total NUMERIC,
    margin NUMERIC,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE sales IS
'ERP Sale_Status 판매내역';

COMMENT ON COLUMN sales.sale_date IS
'ERP Sale_Status.SaleDate';

COMMENT ON COLUMN sales.product_name IS
'ERP Sale_Status.ProductName';

COMMENT ON COLUMN sales.buyer_name IS
'ERP Sale_Status.BuyerCorpNameView';

COMMENT ON COLUMN sales.total_stock IS
'ERP Sale_Status.TotalStock';

COMMENT ON COLUMN sales.unit_cost IS
'ERP Sale_Status.UnitCost';

COMMENT ON COLUMN sales.unit_sale IS
'ERP Sale_Status.UnitSale';

COMMENT ON COLUMN sales.sale_total IS
'ERP Sale_Status.SaleTotal';

COMMENT ON COLUMN sales.margin IS
'ERP Sale_Status.Margin';
